import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
export type BodyData={id:string;nameFa:string;nameEn:string;color:string;radius:number;dist:number;rot:number;desc:string;tags:string[];facts:{label:string;value:string}[];moons:{name:string;r:number;dist:number;period:number}[]};
export const BODIES:BodyData[]=[
{id:"sun",nameFa:"خورشید",nameEn:"SUN",color:"#f59e0b",radius:9,dist:0,rot:.02,desc:"ستارهٔ مرکزی منظومهٔ شمسی و منبع اصلی نور و انرژی آن.",tags:["ستاره","مرکز منظومه"],facts:[{label:"نوع","value":"ستاره"},{label:"دما","value":"≈ ۵۵۰۰°C سطح"}],moons:[]},
{id:"mercury",nameFa:"عطارد",nameEn:"MERCURY",color:"#b8a99a",radius:1.2,dist:15,rot:.03,desc:"کوچک‌ترین سیاره و نزدیک‌ترین سیاره به خورشید.",tags:["سنگی","کوچک"],facts:[{label:"قطر","value":"۴٬۸۸۰ km"},{label:"سال","value":"۸۸ روز"}],moons:[]},
{id:"venus",nameFa:"زهره",nameEn:"VENUS",color:"#e8b36a",radius:2.1,dist:21,rot:.018,desc:"سیاره‌ای سنگی با جو بسیار ضخیم و دمای سطحی بسیار بالا.",tags:["سنگی","جو ضخیم"],facts:[{label:"قطر","value":"۱۲٬۱۰۴ km"},{label:"سال","value":"۲۲۵ روز"}],moons:[]},
{id:"earth",nameFa:"زمین",nameEn:"EARTH",color:"#3fa9f5",radius:2.25,dist:28,rot:.035,desc:"سیارهٔ آبی ما با اقیانوس‌های مایع و تنها جهان شناخته‌شده دارای حیات.",tags:["سنگی","آب","حیات"],facts:[{label:"قطر","value":"۱۲٬۷۴۲ km"},{label:"سال","value":"۳۶۵ روز"}],moons:[{name:"ماه",r:.6,dist:4,period:2}]},
{id:"mars",nameFa:"مریخ",nameEn:"MARS",color:"#d95f45",radius:1.7,dist:36,rot:.034,desc:"سیارهٔ سرخ با سطحی خشک و نشانه‌هایی از آب در گذشته.",tags:["سنگی","سرخ"],facts:[{label:"قطر","value":"۶٬۷۷۹ km"},{label:"سال","value":"۶۸۷ روز"}],moons:[{name:"فوبوس",r:.28,dist:3,period:1},{name:"دیموس",r:.18,dist:4,period:2.5}]},
{id:"jupiter",nameFa:"مشتری",nameEn:"JUPITER",color:"#d6ad82",radius:5.2,dist:52,rot:.08,desc:"بزرگ‌ترین سیارهٔ منظومهٔ شمسی؛ یک غول گازی با طوفان‌های عظیم.",tags:["غول گازی","بزرگ‌ترین"],facts:[{label:"قطر","value":"۱۳۹٬۸۲۰ km"},{label:"سال","value":"۱۱٫۹ سال"}],moons:[{name:"آیو",r:.35,dist:7,period:1.4},{name:"اروپا",r:.3,dist:9,period:2.2},{name:"گانیمد",r:.5,dist:11,period:3.4},{name:"کالیستو",r:.45,dist:14,period:5.5}]},
{id:"saturn",nameFa:"زحل",nameEn:"SATURN",color:"#e3c58e",radius:4.5,dist:68,rot:.07,desc:"غول گازی مشهور به حلقه‌های گسترده و خیره‌کننده‌اش.",tags:["غول گازی","حلقه‌دار"],facts:[{label:"قطر","value":"۱۱۶٬۴۶۰ km"},{label:"سال","value":"۲۹٫۵ سال"}],moons:[{name:"تیتان",r:.5,dist:9,period:2.5}]},
{id:"uranus",nameFa:"اورانوس",nameEn:"URANUS",color:"#7ed8df",radius:3.1,dist:84,rot:.05,desc:"غول یخی با رنگ آبی-سبز و محور چرخشی بسیار متمایل.",tags:["غول یخی","آبی"],facts:[{label:"قطر","value":"۵۰٬۷۲۴ km"},{label:"سال","value":"۸۴ سال"}],moons:[]},
{id:"neptune",nameFa:"نپتون",nameEn:"NEPTUNE",color:"#4779d9",radius:3.05,dist:100,rot:.05,desc:"دورترین سیارهٔ اصلی و دنیایی سرد با بادهای بسیار سریع.",tags:["غول یخی","دورترین"],facts:[{label:"قطر","value":"۴۹٬۲۴۴ km"},{label:"سال","value":"۱۶۵ سال"}],moons:[{name:"تریتون",r:.42,dist:6,period:2.8}]}
];
export class SolarEngine{
 private canvas:HTMLCanvasElement;private labels:HTMLDivElement;private cb:any;private scene=new THREE.Scene();private camera=new THREE.PerspectiveCamera(55,1,.1,1000);private renderer:THREE.WebGLRenderer;private controls:OrbitControls;private groups=new Map<string,THREE.Group>();private labelEls=new Map<string,HTMLElement>();private selected:BodyData|null=null;private raf=0;private clock=new THREE.Clock();private paused=false;private speed=1;private days=0;private disposed=false;private orbits=true;private belt=true;private moons=true;private auto=false;private startTime=performance.now();
 constructor(c:HTMLCanvasElement,l:HTMLDivElement,cb:any){this.canvas=c;this.labels=l;this.cb=cb;this.renderer=new THREE.WebGLRenderer({canvas:c,antialias:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setSize(innerWidth,innerHeight);this.camera.position.set(0,65,120);this.controls=new OrbitControls(this.camera,c);this.controls.enableDamping=true;this.scene.background=new THREE.Color(0x02030a);this.scene.add(new THREE.AmbientLight(0xffffff,.35));const light=new THREE.PointLight(0xffe0a0,5,400);this.scene.add(light);this.makeStars();this.makeBodies();addEventListener("resize",this.resize);cb.onReady?.()}
 private makeStars(){const n=1600,p=new Float32Array(n*3);for(let i=0;i<n;i++){const r=350+Math.random()*300,a=Math.random()*Math.PI*2,b=Math.acos(2*Math.random()-1);p[i*3]=r*Math.sin(b)*Math.cos(a);p[i*3+1]=r*Math.cos(b);p[i*3+2]=r*Math.sin(b)*Math.sin(a)}const g=new THREE.BufferGeometry();g.setAttribute("position",new THREE.BufferAttribute(p,3));this.scene.add(new THREE.Points(g,new THREE.PointsMaterial({color:0xffffff,size:.7,sizeAttenuation:true})));}
 private makeBodies(){BODIES.forEach((b,i)=>{const g=new THREE.Group();const mat=new THREE.MeshStandardMaterial({color:b.color,roughness:.85,emissive:new THREE.Color(b.color).multiplyScalar(b.id==="sun"?.25:.03)});const mesh=new THREE.Mesh(new THREE.SphereGeometry(b.radius,32,20),mat);g.add(mesh);if(b.id==="sun"){mat.emissiveIntensity=2;this.scene.add(new THREE.PointLight(0xffd27a,5,350));}if(b.id==="saturn"){const ring=new THREE.Mesh(new THREE.RingGeometry(b.radius*1.35,b.radius*2.25,96),new THREE.MeshBasicMaterial({color:0xcdbb91,side:THREE.DoubleSide,transparent:true,opacity:.7}));ring.rotation.x=Math.PI/2;g.add(ring)}if(b.dist){g.position.x=b.dist;const pts=[];for(let j=0;j<128;j++){const a=j/128*Math.PI*2;pts.push(new THREE.Vector3(Math.cos(a)*b.dist,0,Math.sin(a)*b.dist))}const line=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:0x52698f,transparent:true,opacity:.35}));this.scene.add(line)}b.moons.forEach(m=>{const mg=new THREE.Group(),mm=new THREE.Mesh(new THREE.SphereGeometry(m.r,16,12),new THREE.MeshStandardMaterial({color:0xaaa8a2}));mm.position.x=m.dist;mg.add(mm);g.add(mg);(mg as any).userData={period:m.period}});g.userData={body:b};this.scene.add(g);this.groups.set(b.id,g);const el=document.createElement("div");el.className="sol-label";el.innerHTML=`<span class="sol-dot" style="background:${b.color}"></span>${b.nameFa}`;el.onclick=()=>this.select(b.id,true);this.labels.appendChild(el);this.labelEls.set(b.id,el)});}
 start(){this.loop()}
 private loop=()=>{if(this.disposed)return;this.raf=requestAnimationFrame(this.loop);const dt=Math.min(this.clock.getDelta(),.05),k=this.paused?0:this.speed;this.days+=dt*k*3;BODIES.forEach(b=>{const g=this.groups.get(b.id)!;if(b.dist){const a=(this.days/(b.dist*b.dist*1.8));g.position.set(Math.cos(a)*b.dist,0,Math.sin(a)*b.dist)}g.rotation.y+=dt*b.rot*k;g.children.forEach(ch=>{if((ch as THREE.Group).userData.period)(ch as THREE.Group).rotation.y+=dt*k/(ch as THREE.Group).userData.period})});this.controls.autoRotate=this.auto;this.controls.autoRotateSpeed=.5;this.controls.update();this.updateLabels();this.renderer.render(this.scene,this.camera);this.cb.onStats?.(this.days)};
 private updateLabels(){for(const b of BODIES){const g=this.groups.get(b.id)!;const e=this.labelEls.get(b.id)!;if(!this.orbits)e.style.opacity="1";const p=g.position.clone().project(this.camera);if(p.z>1||p.z<-1){e.style.display="none";continue}e.style.display="flex";e.style.transform=`translate(${(p.x*.5+.5)*innerWidth}px,${(-p.y*.5+.5)*innerHeight}px) translate(-50%,-120%)`;e.style.opacity=this.selected?.id===b.id?"0":"1"}}
 select(id:string|null,fly=true){this.selected=id?BODIES.find(b=>b.id===id)||null:null;this.labelEls.forEach((e,k)=>e.classList.toggle("active",k===id));if(this.selected&&fly){const g=this.groups.get(this.selected.id)!;this.controls.target.copy(g.position);this.camera.position.copy(g.position).add(new THREE.Vector3(0,this.selected.radius*4+8,this.selected.radius*7+12))}this.cb.onSelect?.(this.selected)}
 setSpeed(v:number){this.speed=v}setPaused(v:boolean){this.paused=v}setOrbits(v:boolean){this.orbits=v}setMoons(v:boolean){this.moons=v;BODIES.forEach(b=>{this.groups.get(b.id)?.children.forEach((x:any)=>{if(x.userData.period)x.visible=v})})}setBelt(v:boolean){this.belt=v}setLabels(v:boolean){this.labels.style.display=v?"block":"none"}setAutoRotate(v:boolean){this.auto=v}resetView(){this.select(null);this.controls.target.set(0,0,0);this.camera.position.set(0,65,120)}capture(){this.renderer.render(this.scene,this.camera);return this.canvas.toDataURL("image/png")}private resize=()=>{this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight)};dispose(){this.disposed=true;cancelAnimationFrame(this.raf);removeEventListener("resize",this.resize);this.controls.dispose();this.renderer.dispose();this.labels.innerHTML=""}}
